---
author: "Sai Kiran Panuganti"
date: "2023-09-24"
output:
  html_document: default
  pdf_document: default
  word_document: default
title: "QMM Assignment 2"
df_print: paged
---

LP Model using R
```{r}
#Installing the lpSolve library
library(lpSolve)

```

```{r}
# Set Objective function
func.objective <- c(420,360,300,
           420,360,300,
           420,360,300)
```

```{r}
#Set the Constraints
func.constraints <-matrix(c(1,1,1,0,0,0,0,0,0,
                 0,0,0,1,1,1,0,0,0,
                 0,0,0,0,0,0,1,1,1,
                 20,15,12,0,0,0,0,0,0,
                 0,0,0,20,15,12,0,0,0,
                 0,0,0,0,0,0,20,15,12,
                 1,0,0,1,0,0,1,0,0,
                 0,1,0,0,1,0,0,1,0,
                 0,0,1,0,0,1,0,0,1) , nrow = 9,byrow = TRUE)
```


```{r}
#Set the direction of the inequalities
func.dir<-c("<=",
         "<=",
         "<=",
         "<=",
         "<=",
         "<=",
         "<=",
         "<=",
         "<=")
```

```{r}
#Set the right hand side coefficients
func.righthandside<-c(750,
        900,
        450,
        13000,
        12000,
        5000,
        900,
        1200,
        750)
```

```{r}
#Find the value of the objective function(Z)
lp("max",func.objective,func.constraints,func.dir,func.righthandside)
```
```{r}
#Values of the variables
lp("max", func.objective, func.constraints, func.dir, func.righthandside)$solution
```
